#!/bin/bash

# for this to work you must add ch2 to the python path in python
# to do this create ~/.ipython/profile_default/ipython_config.py
# and add lines like
#
# c.InteractiveShellApp.exec_lines = [
#     'import sys',
#     'sys.path.append("/home/andrew/project/ch2/choochoo")'
# ]
#
# (obvs your path will be different)

source env/bin/activate
jupyter notebook
