#!/bin/sh
# script generated by
# > /dev/ch2 kit dump --cmd /dev/ch2
/dev/ch2 kit delete --force  bike
/dev/ch2 kit start --force  bike cotic  2016-09-27
/dev/ch2 kit change --force  cotic fork rs-sid   2018-09-05
/dev/ch2 kit change --force  cotic fork-service-lowers rs   2018-09-05
/dev/ch2 kit change --force  cotic fork-service-oil liquimoly   2018-09-05
/dev/ch2 kit change --force  cotic chain pc1110   2019-10-11
/dev/ch2 kit start --force  bike bowman  2019-11-01
/dev/ch2 kit change --force  bowman front-wheel carbonfan   2019-11-01
/dev/ch2 kit change --force  bowman rear-wheel carbonfan   2019-11-01
/dev/ch2 kit change --force  bowman front-tyre schwalbe-pro-1   2019-11-01
/dev/ch2 kit change --force  bowman rear-tyre schwalbe-pro-1   2019-11-01
/dev/ch2 kit change --force  bowman chain kmc-x11   2019-11-01
/dev/ch2 kit change --force  bowman chainset fsa-slk   2019-11-01
/dev/ch2 kit change --force  bowman front-derailleur sram-force-fd   2019-11-01
/dev/ch2 kit change --force  bowman rear-derailleur shimano-xt-rd   2019-11-01
/dev/ch2 kit change --force  bowman cassette hope-42   2019-11-01
/dev/ch2 kit change --force  bowman cassette-large hope-42   2019-11-01
/dev/ch2 kit change --force  bowman brake-cables jagwire-pro-brake   2019-11-01
/dev/ch2 kit change --force  bowman gear-cables jagwire-pro-gear   2019-11-01
/dev/ch2 kit change --force  bowman front-pads spyre-pad   2019-11-01
/dev/ch2 kit change --force  bowman rear-pads spyre-pad   2019-11-01
/dev/ch2 kit change --force  bowman front-sealant stans   2019-11-16
/dev/ch2 kit change --force  bowman rear-sealant stans   2019-11-16
/dev/ch2 kit rebuild
